
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y python3 python3-pip libgl1-mesa-glx

WORKDIR /workspace

COPY ./requirements.txt /workspace/requirements.txt

RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

CMD ["/bin/bash"]
